version: '3'

services:
   mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1435:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Qwerty1234
    container_name: mssql_db

   hadoop-node:
    image: 'ghcr.io/trinodb/testing/hive3.1-hive:79'
    hostname: hadoop-node
    container_name: hadoop-node
    ports:
      - '3306:3306' # Metastore MySQL Database
      - '9083:9083' # Metastore Thrift
      - '9864:9864' # DataNode Web UI since Hadoop 3
      - '9870:9870' # NameNode Web UI since Hadoop 3
      - '10000:10000' # HiveServer2
    volumes:
      - ./hadoop/conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro  

   trino-coordinator-hdfs:
    image: 'trinodb/trino:414'
    hostname: trino-coordinator-hdfs
    container_name: trino-coordinator-hdfs
    ports:
      - '8080:8080'
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/catalog_hdfs:/etc/trino/catalog
      - ./hadoop/conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
      - ./hadoop/conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml:ro