version: '3'

services:
   mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1435:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Qwerty1234
    container_name: mssql_db

   hadoop-node:
    image: 'ghcr.io/trinodb/testing/hive3.1-hive:79'
    hostname: hadoop-node
    container_name: hadoop-node
    ports:
      - '3306:3306' # Metastore MySQL Database
      - '9083:9083' # Metastore Thrift
      - '9864:9864' # DataNode Web UI since Hadoop 3
      - '9870:9870' # NameNode Web UI since Hadoop 3
      - '10000:10000' # HiveServer2
    volumes:
      - ./hadoop/conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro  

   trino-hdfs:
    image: 'trinodb/trino:414'
    hostname: trino-hdfs
    container_name: trino-hdfs
    ports:
      - '8080:8080'
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/catalog_hdfs:/etc/trino/catalog
      - ./hadoop/conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
      - ./hadoop/conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml:ro

   trino-s3:
    image: 'trinodb/trino:414'
    hostname: trino-s3
    container_name: trino-s3
    ports:
      - '8080:8080'
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/catalog_s3:/etc/trino/catalog

   mariadb:
    image: 'mariadb:10.11.2-jammy'
    hostname: mariadb
    container_name: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

   hive-metastore:
    hostname: hive-metastore
    container_name: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb

   minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2023-04-28T18-11-17Z'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_VOLUMES: /mnt/data
    command: server /mnt/data  --console-address ":9001"

   minio-setup:
    depends_on:
      - minio
    image: minio/mc:RELEASE.2023-04-12T02-21-51Z
    container_name: mc
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/datalake;
      /usr/bin/mc mb minio/datalake;
      /usr/bin/mc policy set public minio/datalake;
      exit 0;
      " 